### ISSUE TITLE
Wrong CSS Path

### ISSUE THREAD

**Issue by skazhikadyadya** [petkopara/PetkoparaCrudGeneratorBundle#29] opened 2016-12-17 12:39 UTC
Hi, where I was install as described there your bundle bundle is started, but path to css/js  looks like that:

```
        <!-- Le styles -->
        <link href="/bundles/petkoparaCrudGenerator/css/bootstrap.min.css" rel="stylesheet">
``` 
When I have symlink  `web/bundles/petkoparacrudgenerator`. How I can fix that?

UPD: I was create second symbolic link as 'petkoparaCrudGenerator' but is it right way? )

**Comment by petkopara** [comment] 2016-12-17 13:58
Hi, 
I am not sure, that I understand your problem well. 
Can you be more specific, because I can't find the problem.

**Comment by skazhikadyadya** [comment] 2016-12-17 14:06
Okay. I was installed fresh version of Symfony 3.2, and when it installed symlink at web/bundles was named with wrong directory name (case sensitive). 'petkoparaCrudGenerator' against 'petkoparacrudgenerator'.

**Comment by petkopara** [comment] 2016-12-17 19:31
I couldn't reproduce the issue. What is your operating system?

**Comment by petkopara** [comment] 2016-12-17 20:42
Even I can't reproduce the problem, I understood it and I changed the assets path to lower case names. 
So now the problem should be fixed.

**Closed** 2016-12-22 13:13 UTC
